apiVersion: v1 
kind: Pod 
metadata: 
 name: azurekms 
spec: 
 containers: 
 - name: azurekms 
   image: microsoft/k8s-azure-kms:latest
   imagePullPolicy: Always
   volumeMounts:
   - mountPath: /opt
     name: opt
   - mountPath: /etc/kubernetes
     name: kube
   - mountPath: /etc/ssl/certs/
     name: certs
 volumes:
 - name: opt
   hostPath:
    path: /opt
 - name: kube
   hostPath:
     path: /etc/kubernetes
 - name: certs
   hostPath:
     path: /etc/ssl/certs/